/*
    ARRAY - MÉTODOS 
*/

const students = ['João', 'Maria', 'Pedro', 'Carla', 'Bia', 'Maurício']

// '.push()' ELE ADICIONA ITENS AO MEU ARRAY 
// '.length' ELE ME MOSTRA QUANTOS ITENS TEM NO MEU ARRAY, COMEÇANDO PELO 0
// '.sort()' ELE DEIXA O ARRAY EM ORDEM ALFABÉTICA
// '.delete[]' ELE DELETA UM ITEM DO ARRAY, PORÉM CONTINUA CONTANDO QUE ELE EXISTE

// '.splice()' ELE TIRA ITENS DE ONDE EU QUISER, E ADICIONA ITEM A ONDE EU QUISER, ELE MODIFICA O ARRAY
// '.slice()' ELE PERMITE QUE A GENTE TIRE ITENS DO NOSSO ARRAY, ELE CRIA UM ARRAY, POR ISSO TEMOS QUE CRIAR UMA NOVA VARIAVEL 
// '.pop()' ELE TIRA O ULTIMO ITEM DO ARRY  
// '.shift' ELE TIRA O PRIMEIRO ITEM DO ARRAY 
 
console.log(students)