/*


As APIs(interface de programação de aplicações) elas permite que várias aplciações se comuniquem entre si. Ela é uma padronização 

    API             //  SUA FUNÇÃO É FACILITAR E SIMPLIFICAR O TRABALHO, OFERECE UM PADRÃO PARA CRIAÇÃO DE NOVAS PLATAFORMAS 
    API REST        //  CONJUNTO DE PRINCÍPIOS DE ARQUITETURA    
    API RESTful     //  UMA API QUE SEGUE OS PADRÕES DO REST

    REGRAS REST:

    - CLIENTE - SERVIDOR: AS APLICAÇÕES EXISTENTES NO SERVIDOR E NO CLIENTE DEVEM SER SEPARADAS 
    - SEM ESTADO: AS REQUISIÇÕES SÃO FEITAS DE UMA FORMA IDEPENDENTE, CADA UMA EXECUTA APENAS UMA DETERMINADA AÇÃO 
    - RESPOSTAS AUTODESCRITIVAS, INCLUINDO SUFICIENTE PARA QUE O CLIENTE SAIBA COMO UTILIZÁ-LAS

*/ 